---
- name: Мой первый контакт # Название всей задачи
  hosts: my_servers        # Для каких серверов из инвентаря
  tasks:
    - name: Поздороваться с сервером # Название конкретного шага
      ansible.builtin.ping:           # Встроенный модуль для проверки связи
